baseURL = "https://www.igniting.coach/"
title = "Igniting Coach"
languageCode = "en"

# Exclude footer section from generating list pages (index.html and index.xml)
[outputs]
  page = ["HTML"]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
  footer = []

# Explicitly prevent the footer section from generating any output
[outputFormats.footerSection]
  # Empty configuration to prevent any output

# Specifically disable generation of these kinds for the footer content
disableKinds = ["footerSection", "RSS"]

[module]
[[module.imports]]
path = "github.com/zetxek/adritian-free-hugo-theme"

## Base mounts - so your site's assets are available
[[module.mounts]]
source = "archetypes"
target = "archetypes"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"

# The following mounts are required for the theme to be able to load bootstrap
# Remember also to copy the theme's `package.json` to your site, and run `npm install`
[[module.mounts]]
source = "node_modules/bootstrap/scss"
target = "assets/scss/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js"
target = "assets/js/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/vendor/bootstrap.bundle.min.js"

[[module.mounts]]
source = "node_modules/bootstrap-print-css/css/bootstrap-print.css"
target = "assets/css/bootstrap-print.css"

[[module.mounts]]
source = "node_modules/dompurify/dist/purify.min.js"
target = "static/js/purify.min.js"

[params]
title = 'Igniting Coach'
description = 'Coaching site'
#images = ['/img/og-img.png']
sections = [
  "home",
  "bio",
  "process",
  "testimonial",
  "resources",
  "articles",
]
# If you want to display an image logo in the header, you can add it here
logo = '/img/logo-light.svg'

homepageExperienceCount = 6

[params.analytics]
## Analytics parameters.
### Supported so far: Vercel (Page Insights, Analytics)
### And Google (Tag Manager, Analytics)

# controls vercel page insights - disabled by default
# to enable, just set to true
vercelPageInsights = false
vercelAnalytics = false

# google analytics and tag manager. to enable, set "enabled" to true
# and add the tracking code (UA-something for analytics, GTM-something for tag manager)
[params.analytics.googleAnalytics]
code = "UA-XXXXX-Y"
enabled = false
[params.analytics.googleTagManager]
code = "GTM-XXXXX"
enabled = false

[build]
writeStats = true

[build.buildStats]
enabledFor = ["scss"]
disableClasses = false
disableIDs = false
disableTags = false
enable = true

[params.languages.selector.disable]
footer = false
header = false
mobileHeader = false

[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = 'Igniting Coach'
weight = 0

[languages.en.menus]
[[languages.en.menus.header]]
name = "Home"
URL = "/"
weight = 1

#[[languages.en.menus.header]]
#name = 'Bio'
#URL = '#bio'
#weight = 2

[[languages.en.menus.header]]
name = 'The process'
URL = '#process'
weight = 3

[[languages.en.menus.header]]
name = "Resources"
URL = "/resources"
weight = 4

[[languages.en.menus.header]]
name = "Articles"
URL = "/blog"
weight = 6

[[languages.en.menus.header]]
pre = "email"
name = "email"
URL = "#contact"
weight = 7

[[languages.en.menus.header]]
pre = "linkedin"
name = "linkedin"
URL = "https://www.linkedin.com/in/imalyarenko"
weight = 8

[[languages.en.menus.header]]
pre = "search"
name = "Search"
URL = "/search"
weight = 9

#[[languages.en.menus.header]]
#pre = "user"
#name = "Book"
#URL = "https://cal.com/igniting-coach"
#weight = 10


# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.css]]
URL = "css/adritian-icons.css"
## Print css
[[params.plugins.css]]
URL = "css/bootstrap-print.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"

#[[params.plugins.js]]
#URL = "js/library/fontfaceobserver.js"

# SCSS Plugins
[[params.plugins.scss]]
URL = "scss/adritian.scss"
[[params.plugins.scss]]
URL = "scss/custom.scss"

# theme/color style 
[params.colorTheme]

## the following configuration would disable automatic theme selection
#  [params.colorTheme.auto]
#    disable = true
#  [params.colorTheme.forced]
#    theme = "dark"

## the following parameter will disable theme override in the footer
#  [params.colorTheme.selector.disable]
#  footer = true

[params.colorTheme.selector.disable]
footer = false
header = false
mobileHeader = false
## by default we allow override AND automatic selection

# Page transition settings
[params.pageTransition]
enabled = true  # Set to false to disable the page fade transition effect

[params.blog]
layout = "default"     # options: default (no sidebar), sidebar, sidebar-right
sidebarWidth = "25"    # percentage width of the sidebar
showCategories = true
showRecentPosts = true
recentPostCount = 5
listStyle = "summary"  # options: simple, summary
featured_sort_by_weight = true
featured_sort_by_date = true


[params.experience]
showJobCard = true # Set to false to hide the job card


# Performance optimizations
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    style = "github"

[imaging]
  resampleFilter = "Lanczos"
  quality = 85
  anchor = "Smart"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDefaultAttrVals = true
      keepWhitespace = false
    [minify.tdewolff.css]
      precision = 0
    [minify.tdewolff.js]
      precision = 0