[build.environment]
GO_VERSION = "1.25.0"
HUGO_VERSION = "0.149.0"
NODE_VERSION = "22.18.0"
TZ = "Europe/Oslo"
PATH = "/opt/build/repo/.local/dart-sass:/opt/buildhome/.local/bin:/opt/buildhome/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[build]
publish = "public"
command = "DART_SASS_VERSION=$(curl -sL \"https://api.github.com/repos/sass/dart-sass/releases/latest\" | grep '\"tag_name\":' | sed -E 's/.*\"([^\\\"]+)\".*/\\1/') && curl -sLJO \"https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz\" && tar -C \"${HOME}/.local\" -xf \"dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz\" && rm \"dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz\" && git config core.quotepath false && hugo --gc --minify --baseURL \"${URL}\""